"""Initial Migration

Revision ID: 9422489ef4a2
Revises: 
Create Date: 2024-08-30 19:49:50.523669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9422489ef4a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('registration_confirmation_email', sa.Boolean(), nullable=False),
    sa.Column('profile_pic_name', sa.String(), nullable=True),
    sa.Column('email_token', sa.String(), nullable=True),
    sa.Column('time_token_expired', sa.DateTime(), nullable=True),
    sa.Column('attempts_token_tried', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_time_token_expired'), ['time_token_expired'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('price_of_donation', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_date_posted'), ['date_posted'], unique=False)

    op.create_table('route_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('email_token', sa.String(), nullable=True),
    sa.Column('time_token_expired', sa.DateTime(), nullable=True),
    sa.Column('attempts_token_tried', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_token_time_token_expired'), ['time_token_expired'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_token_time_token_expired'))

    op.drop_table('route_token')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_date_posted'))

    op.drop_table('posts')
    op.drop_table('payments')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_time_token_expired'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
